//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetailSoft.ReporteWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.retailsoft.pucp.org/", ConfigurationName="ReporteWS.ReporteWS")]
    public interface ReporteWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.retailsoft.pucp.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.retailsoft.pucp.org/ReporteWS/generarReporteProveedoresRequest", ReplyAction="http://services.retailsoft.pucp.org/ReporteWS/generarReporteProveedoresResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        RetailSoft.ReporteWS.generarReporteProveedoresResponse generarReporteProveedores(RetailSoft.ReporteWS.generarReporteProveedoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.retailsoft.pucp.org/ReporteWS/generarReporteProveedoresRequest", ReplyAction="http://services.retailsoft.pucp.org/ReporteWS/generarReporteProveedoresResponse")]
        System.Threading.Tasks.Task<RetailSoft.ReporteWS.generarReporteProveedoresResponse> generarReporteProveedoresAsync(RetailSoft.ReporteWS.generarReporteProveedoresRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteProveedores", WrapperNamespace="http://services.retailsoft.pucp.org/", IsWrapped=true)]
    public partial class generarReporteProveedoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public System.DateTime fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public System.DateTime fechaFin;
        
        public generarReporteProveedoresRequest() {
        }
        
        public generarReporteProveedoresRequest(System.DateTime fechaInicio, System.DateTime fechaFin) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteProveedoresResponse", WrapperNamespace="http://services.retailsoft.pucp.org/", IsWrapped=true)]
    public partial class generarReporteProveedoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteProveedoresResponse() {
        }
        
        public generarReporteProveedoresResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteWSChannel : RetailSoft.ReporteWS.ReporteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteWSClient : System.ServiceModel.ClientBase<RetailSoft.ReporteWS.ReporteWS>, RetailSoft.ReporteWS.ReporteWS {
        
        public ReporteWSClient() {
        }
        
        public ReporteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RetailSoft.ReporteWS.generarReporteProveedoresResponse RetailSoft.ReporteWS.ReporteWS.generarReporteProveedores(RetailSoft.ReporteWS.generarReporteProveedoresRequest request) {
            return base.Channel.generarReporteProveedores(request);
        }
        
        public byte[] generarReporteProveedores(System.DateTime fechaInicio, System.DateTime fechaFin) {
            RetailSoft.ReporteWS.generarReporteProveedoresRequest inValue = new RetailSoft.ReporteWS.generarReporteProveedoresRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            RetailSoft.ReporteWS.generarReporteProveedoresResponse retVal = ((RetailSoft.ReporteWS.ReporteWS)(this)).generarReporteProveedores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RetailSoft.ReporteWS.generarReporteProveedoresResponse> RetailSoft.ReporteWS.ReporteWS.generarReporteProveedoresAsync(RetailSoft.ReporteWS.generarReporteProveedoresRequest request) {
            return base.Channel.generarReporteProveedoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<RetailSoft.ReporteWS.generarReporteProveedoresResponse> generarReporteProveedoresAsync(System.DateTime fechaInicio, System.DateTime fechaFin) {
            RetailSoft.ReporteWS.generarReporteProveedoresRequest inValue = new RetailSoft.ReporteWS.generarReporteProveedoresRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((RetailSoft.ReporteWS.ReporteWS)(this)).generarReporteProveedoresAsync(inValue);
        }
    }
}
